### ISSUE TITLE
Requesting amd64 support for JVM library

### ISSUE THREAD

**Issue by Zomis** [eclipse-zenoh/zenoh-kotlin#39]
### Describe the feature

I tried running a simple example with zenoh-kotlin-jvm (0.10.1-rc) today but got this error:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported architecture: amd64
	at io.zenoh.Zenoh$Companion.determineTarget-d1pmJ48(Zenoh.kt:53)
	at io.zenoh.Zenoh$Companion.access$determineTarget-d1pmJ48(Zenoh.kt:29)
	at io.zenoh.Zenoh.<init>(Zenoh.kt:160)
	at io.zenoh.Zenoh.<init>(Zenoh.kt)
	at io.zenoh.Zenoh$Companion.load(Zenoh.kt:36)
	at io.zenoh.Session.<init>(Session.kt:81)
	at io.zenoh.Session.<init>(Session.kt)
	at io.zenoh.Session$Companion.open-d1pmJ48(Session.kt:64)
```

I noticed that `amd64` is not in the list of supported architectures for the JVM library. 😞 

I did manage to build the [zenoh repository itself](https://github.com/eclipse-zenoh/zenoh) without a problem and managed to run the examples. Any reasoning why the JVM library does not support amd64?

System information:

```
Windows 10
Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)

C:\Users\***>echo %PROCESSOR_ARCHITECTURE%
AMD64
```

**Comment by Zomis** [comment]
In the original version of this issue, I incorrectly mentioned `arm64` in a couple of places. Forget everything I said about `arm64`. My processor architecture is `amd64` and nothing else. (I bet I'm not the first one on the internet to mix these up)

**Comment by Zomis** [comment]
I can confirm that this works as of 1.0.0-SNAPSHOT. Thanks for all the help I got on your Discord!
